language: php

php:
    - 5.5

matrix:
    fast_finish: true

branches:
    only:
        - master

sudo: true

before_script:
    - curl --version
    - pear config-set php_ini ~/.phpenv/versions/`php -r 'echo phpversion();'`/etc/php.ini || echo 'Error modifying PEAR'
    - pecl install uri_template || echo 'Error installing uri_template'
    - sudo apt-get install apache2 libapache2-mod-fastcgi

    #- sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
    - sudo service apache2 restart
    - mysql -e 'create database test_codecept;'
    - php -S localhost:8000 -t public/ &
    - sleep 5
    - php codecept.phar build

script:
    - php codecept.phar run api --debug

after_script:
    - mysql -e 'drop database test_codecept;'

notifications:
    email:
        - nilesh.thombare@syntrosys.com
        - kiran.mate@syntrosys.com