language: php

php:
    - 5.6

matrix:
    fast_finish: true

branches:
    only:
        - master

sudo: false

before_script:
    - curl --version
    - pear config-set php_ini ~/.phpenv/versions/`php -r 'echo phpversion();'`/etc/php.ini || echo 'Error modifying PEAR'
    - pecl install uri_template || echo 'Error installing uri_template'
    - composer self-update
    - composer install --no-interaction --prefer-source --dev
    - sudo apt-get install apache2 libapache2-mod-fastcgi

    # enable php-fpm
    - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
    - sudo a2enmod rewrite actions fastcgi alias
    - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  
    # configure apache virtual hosts
    - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
    - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
    - sudo service apache2 restart
    - mysql -e 'create database test_codecept;'
    - php -S localhost:8000 -t public/ &
    - sleep 5
    - php codecept.phar build

script:
    - php codecept.phar run api --debug
  
notifications:
    email:
        - nilesh.thombare@syntrosys.com
        - kiran.mate@syntrosys.com