language: php

php:
    - 5.6

matrix:
    fast_finish: true

branches:
    only:
        - master

sudo: false

before_script:
    - mysql -e 'create database test_codecept;'
    - php -S localhost:8000 -t public/ &
    - sleep 5
    - php codecept.phar build

script:
    - php codecept.phar run api --debug
  
notifications:
    email:
        - nilesh.thombare@syntrosys.com
        - kiran.mate@syntrosys.com