language: php

php:
    - 5.6

matrix:
    allow_failures:
        - php: hhvm
    fast_finish: true

branches:
    only:
        - master

before_script:
    - mysql -e 'create database test_codecept;'
    - php codecept.phar build

script:
    - php codecept.phar run api --debug
  
notifications:
    email:
        - nilesh.thombare@syntrosys.com
        - kiran.mate@syntrosys.com