language: php

php:
    - 5.6

matrix:
    include:
        - php: 5.6
          env: SYMFONY=2.8.0 # latest version of 2.8.*

branches:
    only:
        - master

sudo: false

before_script:
    - mysql -e 'create database test_codecept;'
    - php artisan serve --port=8007 &
    - sleep 5
    - php codecept.phar build

script:
    - php codecept.phar run api --debug
  
notifications:
    email:
        - nilesh.thombare@syntrosys.com
        - kiran.mate@syntrosys.com