language: php

php:
    - 5.2
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0

matrix:
    allow_failures:
        - php: hhvm
    fast_finish: true

branches:
    only:
        - master

before_script:
    - mysql -e 'create database test_codecept;'
    - php -S localhost:8000 -t public &
    - sleep 5 # give artisan serve some time to start
    - php codecept.phar build

script:
    - php codecept.phar run api
  
notifications:
    email:
        - nilesh.thombare@syntrosys.com
        - kiran.mate@syntrosys.com